# agents/email_agent.py
# Send meeting summary emails to attendees with action items and decisions

import os
import sys
import logging
from dotenv import load_dotenv

load_dotenv()
logger = logging.getLogger(__name__)

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from integrations.gmail import send_email, print_email_preview, send_meeting_summary_fallback

load_dotenv()


def format_meeting_summary_email(
    analysis: dict,
    transcript_preview: str = None,
    meeting_data: dict = None
) -> dict:
    """
    Format meeting summary as an email with HTML and plain text versions.

    Args:
        analysis: Analysis dict with summary, action_items, decisions, attendees
        transcript_preview: Optional snippet from transcript
        meeting_data: Optional meeting metadata (file_name, timestamp, meeting_id)

    Returns:
        Dictionary with subject, html_body, text_body, recipients
    """
    summary = analysis.get("summary", "No summary available")
    decisions = analysis.get("decisions", [])
    action_items = analysis.get("action_items", [])
    attendees = analysis.get("attendees", [])

    # Subject line
    subject = f"Meeting Summary: {summary[:60]}..."

    # Build HTML email
    html_body = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <title>{subject}</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 20px; }}
            h2 {{ color: #2c5aa0; }}
            h3 {{ color: #555; margin-top: 20px; }}
            table {{ border-collapse: collapse; width: 100%; margin-top: 10px; }}
            th, td {{ border: 1px solid #ddd; padding: 10px; text-align: left; }}
            th {{ background-color: #f0f0f0; font-weight: bold; }}
            tr:nth-child(even) {{ background-color: #f9f9f9; }}
            .priority-High {{ background-color: #ffebee; }}
            .priority-Medium {{ background-color: #fff9c4; }}
            .priority-Low {{ background-color: #e8f5e9; }}
            .footer {{ margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; color: #777; font-size: 12px; }}
            ul {{ padding-left: 20px; }}
        </style>
    </head>
    <body>
        <h2>📋 Meeting Summary</h2>

        <p>{summary}</p>

        <h3>👥 Attendees</h3>
        <p>{', '.join(attendees) if attendees else 'None recorded'}</p>

        <h3>✅ Decisions Made</h3>
        <ul>
    """

    if decisions:
        for decision in decisions:
            html_body += f"<li>{decision}</li>\n"
    else:
        html_body += "<li>No decisions were recorded</li>\n"

    html_body += """
        </ul>

        <h3>📝 Action Items</h3>
        <table>
            <tr>
                <th>Owner</th>
                <th>Task</th>
                <th>Deadline</th>
                <th>Priority</th>
            </tr>
    """

    if action_items:
        for item in action_items:
            priority = item.get("priority", "Medium")
            html_body += f"""
            <tr class="priority-{priority}">
                <td>{item.get('owner', 'Unassigned')}</td>
                <td>{item.get('task', 'N/A')}</td>
                <td>{item.get('deadline', 'Not specified')}</td>
                <td>{priority}</td>
            </tr>
            """
    else:
        html_body += "<tr><td colspan='4'>No action items identified</td></tr>"

    html_body += """
        </table>
    """

    if transcript_preview:
        html_body += f"""
        <h3>📺 Transcript Preview</h3>
        <pre style="background: #f5f5f5; padding: 10px; border-radius: 5px; overflow-x: auto;">{transcript_preview}</pre>
        """

    if meeting_data:
        html_body += f"""
        <div class="footer">
            <p><strong>Meeting Details:</strong></p>
            <ul>
                <li>File: {meeting_data.get('file_name', 'Unknown')}</li>
                <li>Meeting ID: {meeting_data.get('meeting_id', 'N/A')}</li>
            </ul>
        </div>
        """

    html_body += """
        <p style="margin-top: 30px;">
            <em>This email was generated by <strong>Meeting Copilot</strong> 🤖</em><br>
            <a href="https://github.com/yourusername/meeting-copilot">View on GitHub</a>
        </p>
    </body>
    </html>
    """

    # Plain text version (strip HTML)
    text_body = f"""
Meeting Summary: {summary}

ATTENDEES
{', '.join(attendees) if attendees else 'None recorded'}

DECISIONS
{chr(10).join(f'- {d}' for d in decisions) if decisions else '- No decisions recorded'}

ACTION ITEMS:
"""
    if action_items:
        for item in action_items:
            text_body += f"""
- Owner: {item.get('owner', 'Unassigned')}
  Task: {item.get('task', 'N/A')}
  Deadline: {item.get('deadline', 'Not specified')}
  Priority: {item.get('priority', 'Medium')}

"""
    else:
        text_body += "- No action items identified\n"

    if transcript_preview:
        text_body += f"\nTRANSCRIPT PREVIEW:\n{transcript_preview}\n"

    if meeting_data:
        text_body += f"\nMeeting ID: {meeting_data.get('meeting_id', 'N/A')}\n"

    text_body += "\n--\nMeeting Copilot 🤖\n"

    return {
        "subject": subject,
        "html_body": html_body.strip(),
        "text_body": text_body.strip(),
        "recipients": attendees  # Default: send to attendees
    }


def send_meeting_summary(
    analysis: dict,
    transcript_preview: str = None,
    recipients: list = None,
    meeting_data: dict = None
) -> dict:
    """
    Send meeting summary email to specified recipients.

    Args:
        analysis: Analysis dictionary (from analyzer_agent)
        transcript_preview: Optional snippet from transcript
        recipients: List of email addresses (if None, uses analysis['attendees'])
        meeting_data: Optional additional meeting context

    Returns:
        Dictionary with sent status, message_id, and optional error
    """
    if not analysis:
        return {"sent": False, "error": "No analysis provided"}

    # Format email
    email_content = format_meeting_summary_email(
        analysis=analysis,
        transcript_preview=transcript_preview,
        meeting_data=meeting_data
    )

    # Determine recipients
    if recipients:
        email_recipients = recipients
    else:
        email_recipients = email_content.get("recipients", [])

    if not email_recipients:
        return {"sent": False, "error": "No recipients specified"}

    # Check if Gmail credentials are available
    gmail_api_key = os.getenv("GMAIL_API_KEY") or os.getenv("GOOGLE_CREDENTIALS") or os.path.exists("gmail_credentials.json")

    if gmail_api_key or os.path.exists("gmail_credentials.json"):
        # Try to send via Gmail API
        result = send_email(
            to=email_recipients,
            subject=email_content["subject"],
            html_body=email_content["html_body"],
            text_body=email_content["text_body"]
        )
        return result
    else:
        # Fallback: print to console
        logger.warning(f"\n⚠️  Gmail credentials not found. Printing email preview instead...")
        print_email_preview(
            to=email_recipients,
            subject=email_content["subject"],
            html_body=email_content["html_body"]
        )
        return {
            "sent": False,
            "message_id": None,
            "error": "Gmail credentials not configured - printed to console"
        }


if __name__ == "__main__":
    logger.info("Testing email agent with sample analysis...\n")

    load_dotenv()

    # Sample analysis (similar to what analyzer_agent produces)
    sample_analysis = {
        "summary": "We reviewed the UI design progress and decided to launch v2 in April. John will complete the design by Friday, and Sarah will handle testing by next Monday.",
        "action_items": [
            {
                "owner": "John",
                "task": "Complete UI design",
                "deadline": "2024-04-12",
                "priority": "High"
            },
            {
                "owner": "Sarah",
                "task": "Write test cases and execute testing",
                "deadline": "2024-04-22",
                "priority": "Medium"
            }
        ],
        "decisions": [
            "Proceed with April launch for version 2",
            "Design review will be done by end of week"
        ],
        "attendees": ["John", "Sarah", "Mike"],
        "follow_up_needed": True
    }

    result = send_meeting_summary(
        analysis=sample_analysis,
        transcript_preview="Transcript preview would appear here...",
        recipients=["recipient1@example.com", "recipient2@example.com"]  # Override defaults
    )

    logger.info("\n📊 Email Result:")
    logger.info(json.dumps(result, indent=2))

    if not result["sent"]:
        logger.info("\n💡 Tip: Configure Gmail credentials to actually send emails:")
        logger.info("   1. Go to Google Cloud Console")
        logger.info("   2. Create OAuth 2.0 credentials")
        logger.info("   3. Save as gmail_credentials.json in project root")
